# Generated by Django 4.1 on 2022-09-02 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Domes', '0003_dome_invitationstr_alter_dome_members_and_more'),
        ('posts', '0003_post_dome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='Domes.dome'),
        ),
    ]
