# Generated by Django 4.1 on 2022-09-13 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_comment_reply_to"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"get_latest_by": "-commented", "ordering": ["-commented"]},
        ),
    ]
