# Generated by Django 4.1 on 2022-09-19 07:53

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.user_directory_path, validators=[posts.models.validate_image]),
        ),
    ]
