# Generated by Django 5.2.17 on 2026-09-27 06:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Ready for delivery'), ('processing', 'Attempt in progress'), ('retry', 'Ready to retry'), ('delivered', 'Acknowledged'), ('exhausted', 'Attempt limit reached')], default='pending', max_length=12)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('claim_token', models.UUIDField(editable=False, null=True)),
                ('lease_expires_at', models.DateTimeField(editable=False, null=True)),
                ('last_outcome', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_hash', models.CharField(db_index=True, editable=False, max_length=64)),
                ('slot', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('owner_hash', 'slot'), name='lab_owner_slot_unique'), models.CheckConstraint(condition=models.Q(('slot__gte', 0), ('slot__lte', 2)), name='lab_run_slot_bound')],
            },
        ),
        migrations.CreateModel(
            name='ConsumerReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1500)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='engineering.outboxevent')),
            ],
            options={
                'ordering': ['delivered_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField()),
                ('text', models.CharField(max_length=1500)),
                ('payload_hash', models.CharField(editable=False, max_length=64)),
                ('triage', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='engineering.labrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='engineering.submission'),
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('stage', models.CharField(max_length=40)),
                ('detail', models.CharField(max_length=220)),
                ('duration_ms', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='engineering.outboxevent')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='engineering.labrun')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('run', 'idempotency_key'), name='lab_submission_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='outboxevent',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_count__gte', 0), ('attempt_count__lte', 5)), name='lab_attempt_limit'),
        ),
        migrations.AddConstraint(
            model_name='outboxevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('claim_token__isnull', False), ('lease_expires_at__isnull', False), ('status', 'processing')), models.Q(models.Q(('status', 'processing'), _negated=True), ('claim_token__isnull', True), ('lease_expires_at__isnull', True)), _connector='OR'), name='lab_claim_state_consistent'),
        ),
        migrations.AddConstraint(
            model_name='trace',
            constraint=models.CheckConstraint(condition=models.Q(('duration_ms__gte', 0)), name='lab_trace_nonnegative'),
        ),
    ]
