# Generated by Django 4.0.3 on 2022-04-10 01:17

import Domes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=Domes.models.dome_directory_path_picture)),
                ('banner', models.ImageField(upload_to=Domes.models.dome_directory_path_banner)),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=144)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('privacy', models.IntegerField(choices=[(1, 'Public'), (0, 'Private')], default=1)),
                ('members', models.ManyToManyField(null=True, related_name='server_members', to=settings.AUTH_USER_MODEL)),
                ('moderators', models.ManyToManyField(null=True, related_name='server_moderators', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('Dome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='Domes.dome')),
            ],
        ),
    ]
