# Generated by Django 4.0.3 on 2022-04-10 01:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Domes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dome',
            name='members',
            field=models.ManyToManyField(related_name='server_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dome',
            name='moderators',
            field=models.ManyToManyField(related_name='server_moderators', to=settings.AUTH_USER_MODEL),
        ),
    ]
