# Generated by Django 4.1 on 2022-09-02 22:18

from django.db import migrations, models
from django.utils.crypto import get_random_string


def historical_invitation_default():
    return get_random_string(11)


class Migration(migrations.Migration):

    dependencies = [
        ('Domes', '0003_dome_invitationstr_alter_dome_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dome',
            name='invitationstr',
            field=models.CharField(default=historical_invitation_default, max_length=13, unique=True),
        ),
    ]
