# Generated by Django 4.1 on 2022-09-02 22:18

import Domes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Domes', '0003_dome_invitationstr_alter_dome_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dome',
            name='invitationstr',
            field=models.CharField(default=Domes.models.generate_random, max_length=13, unique=True),
        ),
    ]
