# Generated by Django 4.1 on 2022-09-13 16:37

import Domes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Domes", "0004_alter_dome_invitationstr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dome",
            name="invitationstr",
            field=models.CharField(default=Domes.models.generate_random, max_length=13),
        ),
    ]
