# Generated by Django 4.1 on 2022-09-19 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Domes', '0005_alter_dome_invitationstr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dome',
            old_name='picture',
            new_name='icon',
        ),
    ]
